### ISSUE TITLE
Does not strip single-line comments, these should be removed from the output file regardless of whether compress is specified or not

### ISSUE THREAD

**Issue by doshprompt** [plus3network/gulp-less#174]
LESS:

```less
// Example Comment

@red-color: red;

.text-danger {
  color: @red-color;
}
```

CSS:

```less
// Example Comment
.text-danger {
  color: red;
}
```
