### ISSUE TITLE
URLs broken with relativeUrls: true

### ISSUE THREAD

**Issue by felixfbecker** [plus3network/gulp-less#211]
To show, I made an extremley simple test.js:

``` js
less.render(fs.readFileSync('test.less') + '', {relativeUrls: true, paths: ['node_modules']})
  .then(output => {
    console.log(output.css)
  })

gulp.src('test.less')
  .pipe(gulpLess({relativeUrls: true, paths: ['node_modules']}))
  .pipe(gulp.dest('test'))
```

And the test.less:

``` less
@import 'font-awesome/less/font-awesome';
```

Font-Awesome imports the fonts with a relative url.

The output of the less.render is as expected: All relative urls are correctly rewritten to the cwd:

``` css
@font-face {
  font-family: 'FontAwesome';
  src: url('node_modules/font-awesome/fonts/fontawesome-webfont.eot?v=4.5.0');
  src: url('node_modules/font-awesome/fonts/fontawesome-webfont.eot?#iefix&v=4.5.0') format('embedded-opentype'), url('node_modules/font-awesome/fonts/fontawesome-webfont.woff2?v=4.5.0') format('woff2'), url('node_modules/font-awesome/fonts/fontawesome-webfont.woff?v=4.5.0') format('woff'), url('node_modules/font-awesome/fonts/fontawesome-webfont.ttf?v=4.5.0') format('truetype'), url('node_modules/font-awesome/fonts/fontawesome-webfont.svg?v=4.5.0#fontawesomeregular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

But with gulp-less, the urls in the output file are completely broken:

``` css
@font-face {
  font-family: 'FontAwesome';
  src: url('../../../../../../../../../node_modules/font-awesome/fonts/fontawesome-webfont.eot?v=4.5.0');
  src: url('../../../../../../../../../node_modules/font-awesome/fonts/fontawesome-webfont.eot?#iefix&v=4.5.0') format('embedded-opentype'), url('../../../../../../../../../node_modules/font-awesome/fonts/fontawesome-webfont.woff2?v=4.5.0') format('woff2'), url('../../../../../../../../../node_modules/font-awesome/fonts/fontawesome-webfont.woff?v=4.5.0') format('woff'), url('../../../../../../../../../node_modules/font-awesome/fonts/fontawesome-webfont.ttf?v=4.5.0') format('truetype'), url('../../../../../../../../../node_modules/font-awesome/fonts/fontawesome-webfont.svg?v=4.5.0#fontawesomeregular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

What could cause this?
