### ISSUE TITLE
@{variable} outputs hex value if contains a "-" followed by number

### ISSUE THREAD

**Issue by Blue-EyesWhiteDragon** [plus3network/gulp-less#225]
The following:

```less
// Reds
@red: #E74C3C;
@red-2: #C0392B;

// Oranges
@orange: #F39C12;
@orange-2: #E67E22;
@orange-3: #D35400;

// Yellows
@yellow: #F1C40F;

// Greens
@green: #2ECC71;
@green-2: #27AE60;

// Turquoise
@turquoise: #1ABC9C;
@turquoise-2: #16A085;

// Blues
@blue: #3498DB;
@blue-2: #2980B9;

// Purples
@purple: #9B59B6;
@purple-2: #8E44AD;

// Navy Blues
@navy: #34495E;
@navy-2: #2C3E50;

// Greys
@grey: #ECF0F1;
@grey-2: #BDC3C7;
@grey-3: #95A5A6;
@grey-4: #7F8C8D;

@colour-scheme:
	red, red-2,
	orange, orange-2, orange-3,
	yellow,
	green, green-2,
	turquoise, turquoise-2,
	blue, blue-2,
	purple, purple-2,
	navy, navy-2,
	grey, grey-2, grey-3, grey-4
;

.createButtonColour(@colour){
	background-color: @colour;
	border: 1px solid darken(@colour, 7.5%);
	&:hover, &:active, &:target, &:focus{
		background-color: darken(@colour, 5%);
	}
}

.createButtonColours(@colour-array: @colour-scheme, @n: length(@colour-scheme), @i: 1 ) when (@i <= @n){
	@colour: extract(@colour-array, @i);
	&.@{colour}{
		background-color: @@colour;
	}
	.createButtonColours( @colour-array, @n, @i + 1 )
}

.button{
	font-weight: 600;
	color: #f5f5f5;
	border-radius: 3px;
	margin: .25em;
	padding: .5em 1em;
	transition: background-color .2s ease-in-out;
	.createButtonColour(#666);
	.createButtonColours();
}
```

Should output:

```less
.button {
  font-weight: 600;
  color: #f5f5f5;
  border-radius: 3px;
  margin: .25em;
  padding: .5em 1em;
  transition: background-color 0.2s ease-in-out;
  background-color: #666;
  border: 1px solid #535353;
}
.button:hover,
.button:active,
.button:target,
.button:focus {
  background-color: #595959;
}
.button.red {
  background-color: #E74C3C;
}
.button.red-2 {
  background-color: #C0392B;
}
.button.orange {
  background-color: #F39C12;
}
.button.orange-2 {
  background-color: #E67E22;
}
.button.orange-3 {
  background-color: #D35400;
}
.button.yellow {
  background-color: #F1C40F;
}
.button.green {
  background-color: #2ECC71;
}
.button.green-2 {
  background-color: #27AE60;
}
.button.turquoise {
  background-color: #1ABC9C;
}
.button.turquoise-2 {
  background-color: #16A085;
}
.button.blue {
  background-color: #3498DB;
}
.button.blue-2 {
  background-color: #2980B9;
}
.button.purple {
  background-color: #9B59B6;
}
.button.purple-2 {
  background-color: #8E44AD;
}
.button.navy {
  background-color: #34495E;
}
.button.navy-2 {
  background-color: #2C3E50;
}
.button.grey {
  background-color: #ECF0F1;
}
.button.grey-2 {
  background-color: #BDC3C7;
}
.button.grey-3 {
  background-color: #95A5A6;
}
.button.grey-4 {
  background-color: #7F8C8D;
}
```

Like it does on this [less2css.org example](http://goo.gl/VkG1rk)

Except gulp-less (v. 3.0.5) gives me the error `variable @undefined is undefined` on the line where `@@colour` is mentioned. Now - forgetting this other issue - if I remove this and replace it with a `width: 0px`, just to check my compiled css has compiled it correctly, it outputs this:

```less
.button {
  font-weight: 600;
  color: #f5f5f5;
  border-radius: 3px;
  margin: .25em;
  padding: .5em 1em;
  transition: background-color 0.2s ease-in-out;
  background-color: #666;
  border: 1px solid #535353;
}
.button:hover,
.button:active,
.button:target,
.button:focus {
  background-color: #595959;
}
.button.red {
  width: 0px;
}
.button.#fd0000 {
  width: 0px;
}
.button.orange {
  width: 0px;
}
.button.#fda300 {
  width: 0px;
}
.button.#fca200 {
  width: 0px;
}
.button.yellow {
  width: 0px;
}
.button.green {
  width: 0px;
}
.button.#007e00 {
  width: 0px;
}
.button.turquoise {
  width: 0px;
}
.button.#3edece {
  width: 0px;
}
.button.blue {
  width: 0px;
}
.button.#0000fd {
  width: 0px;
}
.button.purple {
  width: 0px;
}
.button.#7e007e {
  width: 0px;
}
.button.navy {
  width: 0px;
}
.button.#00007e {
  width: 0px;
}
.button.grey {
  width: 0px;
}
.button.#7e7e7e {
  width: 0px;
}
.button.#7d7d7d {
  width: 0px;
}
.button.#7c7c7c {
  width: 0px;
}
```

Am I the only one experiencing this issue?
