### ISSUE TITLE
@extend error

### ISSUE THREAD

**Issue by ronaldohoch** [plus3network/gulp-less#254]
Hello, thank you for this plugin.
The following code don't work.:

```css
.text-ellipsis{
	display: inline-block;
	overflow: hidden;
	text-overflow: ellipsis;
	white-space: nowrap;
}

a{
@extend .text-ellipsis;
}

b{
  @extend .text-ellipsis;
  width:100%;
}
```

Cause the export came with
```css
b{
  @extend .text-ellipsis;
  width:100%;
}
```

But here in http://www.sassmeister.com/, the above code works.
