### ISSUE TITLE
threshold doesn't work in contrast() function 

### ISSUE THREAD

**Issue by henrysun918** [plus3network/gulp-less#255]
The [example ](http://lesscss.org/functions/#color-operations-contrast) in the official website yields a different output than the expected one.

Source: 
```less
p {
    a: contrast(#bbbbbb);
    b: contrast(#222222, #101010);
    c: contrast(#222222, #101010, #dddddd);
    d: contrast(hsl(90, 100%, 50%), #000000, #ffffff, 30%);
    e: contrast(hsl(90, 100%, 50%), #000000, #ffffff, 80%);
}
```

Expect output:
```less
p {
    a: #000000 // black
    b: #ffffff // white
    c: #dddddd
    d: #000000 // black
    e: #ffffff // white
}
```

Actual output:
```less
p {
  a: #000000;
  b: #ffffff;
  c: #dddddd;
  d: #000000;
  e: #000000; // this is wrong
}
```

Environment:
`"gulp-less": "^3.1.0"`

The same source compiles just fine using the `less 2.5.3` [live demo](http://less2css.org/).
